import turtle
turtle.shape('turtle')

#Смайлик
eye=20 #радиус глаза
face=100 #радиус лица
turtle.penup()
turtle.goto(face, 0)
turtle.left(90)
turtle.pendown()
turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(face)
turtle.end_fill()
turtle.penup()
turtle.goto(face/4 + eye, face/2)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(eye)
turtle.end_fill()
turtle.penup()
turtle.goto(-face/4 + eye, face/2)
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(eye)
turtle.end_fill()
turtle.penup()
turtle.color('black')
turtle.width(5)
turtle.goto(0, face/4)
turtle.pendown()
turtle.back(face/2)
turtle.penup()
turtle.goto(face/2, -face/4)
turtle.left(180)
turtle.color('red')
turtle.pendown()
turtle.circle(-face/2, 180)

turtle.done()